### ISSUE TITLE
index.ts 에 구현되어 있는 로직에 대한 질문

### ISSUE THREAD

**Issue by yunseorim1116** [tree-s-computer/jwt#1]
1. base64urlEscape 함수를 실행하는게 URL 에 유효한 문자를 사용하기 위해서가 맞는것인가요 ?

2. jwtWebToken 이라는 라이브러리가 존재하는데 , 깃 레포에 있는 로직은 직접 만드신 로직인가요 ? 
또는 jwtWebToken 과 어떤 차이가 있는지?

3. index.ts 32번째줄 unsignedToken (서명되지 않은 토큰) 이라는 이름을 지은 이유는 무엇인가요 ?

정답을 알려주셔도 좋고, 
이러한 문서를 참고하시면 좋을 것 같다, 이 키워드를 통해 공부해봐도 좋을 것 같다 라고 남겨주셔도 좋습니다!

**Comment by lukasjhan** [comment]
@yunseorim1116 

1. 맞아요. url safe하게 만들기 위해서에요.
2. 다른 라이브러리랑 로직은 거의 같아요. 대신 제가 만든로직은 sign하는 기능만 있어요. 다른 라이브러리에는 verify하는 기능도 있을거에요. 특히 verify할때 exp 값, 즉 만료되었는지도 대부분 확인합니다.
3. jwt가 항상 서명을 포함해야하는것은 아니에요. 따라서 서명을 제외한 부분을 서명되지 않은 토큰으로 이름 붙였어요.

**Comment by yunseorim1116** [comment]
이해됐습니다. 설명해주셔서 감사해요!
