### ISSUE TITLE
base64urlEscape 

### ISSUE THREAD

**Issue by yunseorim1116** [tree-s-computer/jwt#2]
`function base64urlEscape(str: string) {
  // Remove padding equal characters and replace characters according to base64url specifications
  return str.replace(/\+/g, "-").replace(/\//g, "_").replace(/=/g, "");
}`
해당 함수에 대한 질문입니다.
찾아보니 " 이 = 문자는, url-safe 하지 않으므로, 제거되어야 합니다. " 라고 합니다.

### url-safe 하지 않다는 의미가 정확히 무엇일까요 ?

url 에 정보가 제대로 숨겨지지 않는다는 의미인가요 ? 
'=' 이 문자는 숨겨지지 않아도 상관 없는 것 아닌가요? 
query?=test 
이런식으로 표현이 될때 = 문자열이 문제가 생길 수 있어서 다른 문자열로 대체해야 하는 것인가요 ?

**Comment by lukasjhan** [comment]
`=` 문자는 URL에서 사용처가 정해져있습니다. URL 스펙에 정해져있죠. 쿼리에서 사용됩니다.
`/` 문자도 그렇습니다. Path를 구분하죠.
`+` 문자는 공백을 나타냅니다. 

따라서 이들를 다른문자로 변경하는것입니다. URL safe한 문자는 알파벳, 숫자, `-`, `.`, `_`, `~` 입니다.

https://www.ietf.org/rfc/rfc3986.txt 표준문서의 2.3섹션에 보시면 예약된 문자들이 있습니다.

**Comment by lukasjhan** [comment]
위 기호는 각각 빼기, 쩜, 언더바, 틸드 문자입니다. :)

**Comment by yunseorim1116** [comment]
이해했습니다. 답해주셔서 감사합니다!
